### ISSUE TITLE
Kanály CS

### ISSUE THREAD

**Issue by mdobes** [MarhyCZ/picons#10]
Ahoj 👋,
od 1. prosince máme rebrandy kanálu CS Film, CS Mini, Horor film (CS Horror), Kinosvět (CS Mystery) a WAR Svět válek (CS History). Až bude někdy čas, mohl by si se na to prosím podívat (https://digital.rozhlas.cz/zahajuji-stanice-cs-mystery-cs-history-a-cs-horror-k-dispozici-budou-pro-8116824)?

Předem díky!
Michal.

**Comment by MarhyCZ** [comment]
Díky za info, určitě na to mrknu.
Vysílá se už s novými logy? 

Michal

**Comment by mdobes** [comment]
Ano, od 1. prosince (tu je když tak malá ukázka: https://www.youtube.com/watch?v=o9sjR4xrf6I).

Michal.

**Comment by MarhyCZ** [comment]
Nový commit ea3a19af0d4fa3a3dc21c0d744d6ff6ad244bfc0
Odebral jsem staré kanály CS Film, CS Mini, TV War, Kino Svět, Horror Film
Přidal rebrandy CS Film, CS History, CS Mystery, CS Horror

Pravděpodobně bude v Tvheadend nutné buď zadat URL adresu pro nové ikonky u kanálů ručně, nebo kliknout na "Reset icon" u všech CS kanálů a poté na "uložit" Dojde k vygenerování nové URL.

**Comment by mdobes** [comment]
Díky! :)
