### ISSUE TITLE
Nové kanály

### ISSUE THREAD

**Issue by mdobes** [MarhyCZ/picons#11]
Ahoj Mahry!
Rád bych tě poprosil o loga nových kanálů.

- nicktoons (https://img.favpng.com/9/23/5/nickelodeon-nick-jr-too-nicktoons-polska-png-favpng-mMipXheQEYspikig9iTQd1dmt.jpg)
- Comedy House (https://i1.wp.com/www.broadbandtvnews.com/wp-content/uploads/2019/12/Comedy-House.png?resize=1033%2C900&ssl=1)

Předem díky,
Michal! :)

**Comment by MarhyCZ** [comment]
Poslední commit e54e3a47c76980b5cef3118695fc3b2191c44c19 - Oba kanály byly přidány.

Měj se,
M.
