### ISSUE TITLE
Orange sport 2, 3, 4 

### ISSUE THREAD

**Issue by sonics007** [MarhyCZ/picons#14]
Ahoj vedel by si urobit tieto picony?
btw skvela praca

**Comment by MarhyCZ** [comment]
Ahoj, díky moc:)

Mohu na to mrknout, ale nikdy na internetu nevidím jak tenhle logotyp vypadá. Máš screenshot z vysílání?

**Comment by sonics007** [comment]
Mam toto![image](https://user-images.githubusercontent.com/5091071/94316909-8bd5cf80-ff85-11ea-8b9f-d09a6835f989.png)

**Comment by MarhyCZ** [comment]
Chtěl jsem prosím z vysílání, ne z programu. Tedy pusť si jeden z těch kanálů a udělej mi screenshot. Díky.

**Comment by sonics007** [comment]
Ani jeden nevysiela musime pockat ked bude nieco na programe

**Comment by sonics007** [comment]
![image](https://user-images.githubusercontent.com/5091071/94339046-4520bd80-fff7-11ea-9ba8-835b2ad60ab0.jpeg)

**Comment by MarhyCZ** [comment]
Orange Sport ukončila činnost, takže sem byl pomalejší.
