### ISSUE TITLE
TV Paprika

### ISSUE THREAD

**Issue by zendiik** [MarhyCZ/picons#21]
Ahoj,

TV Paprika má nové logo, mohl bys ho aktualizovat?

Díky

**Comment by MarhyCZ** [comment]
Ahoj, moc díky za info. Aktualizováno. Bohužel jsem neměl dřív chvilku to udělat.
Našel jsi ještě jiná loga co prošla aktualizací?

Měj se,
M

**Comment by zendiik** [comment]
Nenašel, díky :)
