### ISSUE TITLE
Ikony na GitHub Pages už nefungují

### ISSUE THREAD

**Issue by ondrejmirtes** [MarhyCZ/picons#4]
Např. https://marhycz.github.io/picons/640/o2tvfotbalhd.png - 404 page not found

**Comment by MarhyCZ** [comment]
Kouknu na to :)

**Comment by MarhyCZ** [comment]
Prosím ověřte si nejdříve, jestli tam vůbec takový soubor mám. 
Ikony fungují.
https://marhycz.github.io/picons/640/ct1.png
https://marhycz.github.io/picons/640/o2tvfotbal.png

Není tam akorát zástupce na o2tvfotbalhd.png. Později ho přidám

**Comment by ondrejmirtes** [comment]
Jo, díky, pardon. Zmátlo mě, že tu cestu vygeneroval skript pro O2TV playlist, a na samotném `https://marhycz.github.io` taky nic nebylo 😊
