### ISSUE TITLE
Chybí ikonky Barrandov Family a Rebel 2: Slušnej kanál

### ISSUE THREAD

**Issue by jzobac** [MarhyCZ/picons#5]
Ahoj,
můžeš prosím přidat ikonky pro Barrandov Family a Rebel 2: Slušnej kanál?

díky JZ

**Comment by MarhyCZ** [comment]
Ahoj, 
Prosím před podáním issue, aby se každý kouknoul nejdříve jestli to tam opravdu není. 
Oba dva kanály tam jsou. familybarrandov a rebel2.

Označení ikonek beru podle názvů kanálů ze satelitu.

Děkuji.

**Comment by MarhyCZ** [comment]
Můžeš mi sem ale hodit, jaké názvy souborů ti vygeneroval tvheadend, nebo jiný klient a já mohu vytvořit zástupce na původní ikonku (symlink)

**Comment by jzobac** [comment]
Díky, již jsem je našel, je to lehce nesystematické, hledat např. Barrandov pod mutacema (satelit nemám; dle mého je lepší nazvat vše např. Barrandov a poté TV, Family apod...). Na hlavní stránce githubu také chybí, proto jsem se domníval že nejsou,

TVH vygeneroval z DVBT1/2: rebel2slusnejkanal a barrandovfamily

JZ

**Comment by MarhyCZ** [comment]
Chápu vás, u mě není cílem systematičnost, ale aby se co nejvíce kanálů přiřadilo samo bez potřeby to upravovat v TVH. 
Ale díky za info, přidám tam dnes zástupce na tyhle dvě varianty! :) 

Mějte se.
M
