### ISSUE TITLE
DVB-T2 linky

### ISSUE THREAD

**Issue by michformanek** [MarhyCZ/picons#6]
Ahoj,

Mohl bys prosím přidat ikonku pro [V1](https://1gr.cz/fotky/idnes/12/081/org/KOL450c52_v1tv_logo2.PNG)

A také by se hodily linky pro dvt-t2, mux 12,13 (nova, prima,...)

Mockrát díky :)

**Comment by MarhyCZ** [comment]
Ahoj,

určitě! Pošleš mi tedy prosím názvy ikonek, které ti Tvheadend vygeneroval? (Pokud ho používáš). 
jestli to mám pojmenovat jako v1t2.png novat2.png,...?

**Comment by michformanek** [comment]
Je to jen výstup z GREP, takže je možné že tam něco bude opakovat, nebo že pro některé už linky jsou. Konkrétně V1 pro dvbt2 ještě přidává do názvu HD - tj. mělo by být v1.png a v1hdt2.png

Díky!

barrandovfamilyt2.png
barrandovplust2.png
barrandovtvt2.png
croddurt2.png
crodvojkat2.png
crojazzt2.png
croplust2.png
croradiojuniort2.png
croradiowavet2.png
croradiozurnalt2.png
crovltavat2.png
ct1hdt2.png
ct24hdt2.png
ct2hdt2.png
ctdarthdt2.png
ctsporthdt2.png
jojfamilyhdt2.png
kinobarrandovt2.png
kinosvett2.png
noetvt2.png
nova2t2.png
novaactiont2.png
novacinemat2.png
novagoldt2.png
novat2.png
ockostart2.png
ockot2.png
primacomedycentralhdt2.png
primacoolt2.png
primakrimit2.png
primalovet2.png
primamaxt2.png
primat2.png
primazoomt2.png
proglast2.png
seznamcztvt2.png
slagr2t2.png
slagrtvt2.png
tvrebelt2.png
tvrelaxt2.png
v1hdt2.png

**Comment by rdolezel** [comment]
Ahoj,
narazil jsem na stejný problém, nakonec jsem v konfiguraci EPG u všech programů z MUXu 11, 12, 13 odmazal řetězec "t2"a šmitec.

Každopádně posílám ještě můj seznam:
barrandovtvt2.png
barrandovkrimit2.png
barrandovnewst2.png
croddurt2.png
crodvojkat2.png
crojazzt2.png
croplust2.png
croradiojuniort2.png
croradiowavet2.png
croradiozurnalt2.png
crovltavat2.png
ct1hdt2.png
ct2hdt2.png
ct24hdt2.png
ctdarthdt2.png
ctsporthdt2.png
jojfamilyhdt2.png
kinosvett2.png
kinobarrandovt2.png
novacinemat2.png
novat2.png
noetvt2.png
nova2t2.png
novaactiont2.png
novagoldt2.png
ockostart2.png
ockot2.png
primacoolt2.png
primacomedycentralhdt2.png
primakrimit2.png
primalovet2.png
primamaxt2.png
primazoomt2.png
primat2.png
proglast2.png
seznamcztvt2.png
slagr2t2.png
slagrtvt2.png
tvrebelt2.png
tvrelaxt2.png
v1hdt2.png

**Comment by MarhyCZ** [comment]
Vidíte, 
úplně jsem na to zapomněl během zkouškového. Díky Vám moc za seznamy! Dneska udělám commit.

**Comment by MarhyCZ** [comment]
Tak v posledním commitu dbfb8a7ec2d5b34af9c3636ece2ef6f6a2e77568 jsem přidal podle vás hardlinky na T2 verze kanálů. Zároveň jsem přidal nové logo barrandovkrimi.png 
A znovu se kouknu po vektorovém logu V1 a proglasu. 

Jestli budete mít čas, můžete to vyzkoušet, zda se to přiřazuje samo. Mějte se.

**Comment by rdolezel** [comment]
Zresetoval jsem ikony a vše šlape. Nově se načítá i Barrandov News (jen pro úplnost informace, nepředpokládám, že někdo, kdo má mozkovou kapacitu na zprovoznění Tvheadend, by koukal na jakýkoliv *Barrandov* kanál). Z TV stanic tedy chybí jen V1.
Dobrá práce, díky.

**Comment by MarhyCZ** [comment]
Tak super! Dobrá poznámka :-D Alespoň právě vidíme tu ikonku a můžeme ten kanál rychleji přepnout.

Kouknu na V1 a proglas a až to bude, tak uzavřu issue. 

Za málo, jsem rád, že to někdo využívá :-)

**Comment by MarhyCZ** [comment]
Přidáno V1 f8fc1765e2987ee6d20b396f00cf8adf825083e1

**Comment by MarhyCZ** [comment]
A v ba6693fbaccc3b2478ae1e81179a5ec5167c9ebc přidávám Radio Proglas. Takže všechny ikonky by už měli korektně běžet. 
Proto uzavírám. Kdyby něco, stačí issue znovu otevřít.
