### ISSUE TITLE
ČT 1 SM/JM

### ISSUE THREAD

**Issue by stefanides** [MarhyCZ/picons#7]
Ahoj, 

DVB-T(1) tu s námi ještě chvíli bude, na severní a jižní Moravě vysílá pozemní ČT1 s regionálním názvem, tj. aby vše fungovalo bez dodatečných úprav, chtělo by to zkopírovat obrázek ještě jako 
```
ct1sm.png
ct1jm.png
```

A jak se dívám, na skylinku má regionální verze taky, ale už v HD (viz https://en.kingofsat.net/find.php?question=CT+1), tj. potom ještě taky
```
ct1smhd.png
ct1jmhd.png
```

Díky :-)

**Comment by MarhyCZ** [comment]
Ahoj,
vidíš, ty jsem si v Tvheadendu schoval, takže mi nikdy nedošlo, že jim chybí loga. Dobrý postřeh!

Díky moc za názvy souborů, hned to tam hodím :)

**Comment by MarhyCZ** [comment]
Zástupci přidáni v 6f6eca0f062084b7a44814da70f673a6ee00da54

Ale v tomhle případě není změna jen v kvalitě (HD x SD), ale obsahová, tak uživatel může používat obě verze najednou. 
Nehodilo by se v tomto případě tedy vytvořit varianty loga s textem JM a SM pod logem jedničky?

**Comment by stefanides** [comment]
> Ale v tomhle případě není změna jen v kvalitě (HD x SD), ale obsahová, tak uživatel může používat obě > verze najednou.
> Nehodilo by se v tomto případě tedy vytvořit varianty loga s textem JM a SM pod logem jedničky?

V pozemáku to mixovat nejde (možná někde na hraně vysílačů), jestli někdo používá víc verzí ze satelitu těžko říct - většinou ho zprávy z cízího regionu nebudou moc zajímat a v oblíbených bude mít stejně jen jeden z nich :-) Ale smysl to nejspíš má - potom by možná mělo smysl rozlišovat i obrázek SD/HD, protože naopak v pozemáku teď vysílají současně a T2 tuner je naladí obě verze. (ale to mně netrápí, protože to filtruju taky už v tvheadend)

**Comment by MarhyCZ** [comment]
Máš pravdu, pozemák bude omezený. Na satelitu to není omezené, ale nikdo asi nebude sledovat jiné verze (sám jsem toho příkladem). V tom případě to dělat nebudu. 

Právě HD verze nedělám, protože to neberu tak co člověk naladí, ale co používá poté co si udělá svůj seznam kanálů. Takže počítám s tím, že každý člověk si vybere pro sebe tu nejlepší verzi co má k dispozici a nebude aktivně používat SD a HD verzi zároveň. Pak je zbytečené dělat HD příznaky, protože to jen zmenšuje ostatní část loga a logo pak není hezky vycentrované. 

Díky moc za info a měj se! 
Uzavírám issue, kdyby něco, stačí to znovuotevřít :-)

**Comment by stefanides** [comment]
:+1:
