### ISSUE TITLE
ČT 1 SM/JM HD T2

### ISSUE THREAD

**Issue by stefanides** [MarhyCZ/picons#9]
ahoj, od včerejška máme další regionální verze ČT1 - "CT 1 SM HD T2",  "CT 1 JM HD T2" (od skylinku se liší přidaným T2).  Po novém roce budou ještě další dvě "CT 1 SVC HD T2", "CT 1 JZC HD T2" - asi se dají přidat rovnou, viz např. http://www.televizniweb.cz/2019/10/jak-bude-ceska-televize-resit-regionalni-vysilani-v-dvb-t2-planuje-hned-pet-mutaci-zprav/ . Všude stačí i kopie stávajícího obrázku. Časem asi zmizí to T2, ale ještě nikdo neví, jestli a kdy :-)

(viz taky https://github.com/MarhyCZ/picons/issues/7, reopen mi nejde)

**Comment by MarhyCZ** [comment]
Ahoj, 
hoď mi prosím jména souborů a hned to tam přidám :) 

Měj se

**Comment by stefanides** [comment]
Jména souborů jsou předpokládám automatické - vše za sebou bez mezer? :-) 
ct1jmhdt2.png apod.

**Comment by pschonmann** [comment]
cp retromusictv.png retromusictvt2.png
cp seznamcztvt2.png seznamcztvhdt2.png
cp relax.png relaxt2.png
cp rebel.png rebelt2.png
cp rebel2slusnejkanal.png rebel2slusnejkanalt2.png
cp jojfamily.png jojfamilyt2.png
cp barrandovnewst2.png barrandovnews.png
cp ct1smhd.png ct1smhdt2.png
cp primaplus1.png primaplus1t2.png
cp csmystery.png csmysteryt2.png
cp ct1jmhd.png ct1jmhdt2.png

**Comment by MarhyCZ** [comment]
Vidíte, úplně mi to vypadlo, dííky moc!!
Hardlinky doplněny. Ještě něco hapruje v DVB-T2?
